import { z } from 'zod'

// ===== Enums =====
export const LocalidadeEnum = z.enum([
  'AIUA',
  'IPAGUACU_MIRIM',
  'LOCALIDADE_CACIMBA_VELHA',
  'ARARINHA',
  'ARRAIAL',
  'BAIXIO',
  'CACIMBINHA',
  'CAMPESTRE',
  'CASA_FORTE',
  'CONTENDAS',
  'CURU',
  'FAZENDINHA',
  'GREGORIO',
  'GROSSOS',
  'JATOBA',
  'MADEIRO',
  'MERUOQUINHA',
  'MORGADO',
  'PASSAGEM',
  'PAUS_BRANCO',
  'PE_DA_SERRA',
  'RAIZ',
  'RIACHAO_DOS_FARIAS',
  'RIACHO_FUNDO',
  'RIO_DO_CANTO',
  'SALGADINHO',
  'SANTA_LUZIA',
  'SANTO_AMARO',
  'SAO_DAMIAO',
  'TAPERA_ALTA',
  'TAPERA_BAIXA',
  'TERRA_NOVA',
  'TRAPIA',
  'VASSOURAS',
  'VAZEA_DA_CRUZ',
  'MUMBABA',
  'PADRE_LINHARES',
  'TANGENTE',
  'TUINA',
  'ALTO_DA_BOA_VISTA',
  'ALTO_DA_CADEIA',
  'BAIRRO_CAMPO_DO_MILLE',
  'BAIRRO_DO_CEMITÉRIO',
  'BANDEIRA_BRANCA',
  'CARTUCHA',
  'CENTRO',
  'COHAB',
  'CORTE_DO_ANANÁS',
  'CRUZEIRO',
  'LUIZ_DA_HORA_PEREIRA',
  'MANIVAO',
  'MARAMBAIA',
  'MUMBABA_DE_BAIXO',
  'MUMBABA_DE_CIMA',
  'NOSSA_SENHORA_DE_FATIMA',
  'RODAGEM',
  'SANTA_URSULA',
  'TAMANDUA',
])

export const PapelEnum = z.enum([
  'ADMINISTRADOR',
  'CIDADAO',
  'GESTOR',
  'PROFISSIONAL',
  'SECRETARIO',
])

// ===== Usuario Schema =====
export const userCadastroSchema = z.object({
  data_nascimento: z.string().optional(),
  nome_mae: z.string().min(3, 'O nome da mãe deve ter pelo menos 3 caracteres').optional(),
  id: z.string().optional(),
  nome: z.string().min(3, 'O nome deve ter pelo mxenos 3 caracteres'),
  localidade: LocalidadeEnum,
  numero_casa: z.string().optional(),
  rua: z.string().optional(),
  rg: z.string().length(9),
  complemento: z.string().optional(),
  cpf: z.string().min(11, 'O CPF deve conter pelo menos 11 caracteres'),
  nis: z.string().min(11, 'O NIS deve conter pelo menos 11 caracteres'),
  senha: z.string().min(8, 'A senha deve ter pelo menos 6 caracteres'),

  // relacionamentos
  assistencia: z.any().optional(),
  solicitacoes: z.array(z.any()).optional(),
  configuracao: z.any().optional(),
  atividades: z.array(z.any()).optional(),
  ouvidorias: z.array(z.any()).optional(),
})

export type userCadastroDTO = z.infer<typeof userCadastroSchema>
